openapi: 3.1.0
info:
  title: Charge Planning Optimizer API
  version: 1.0.0
  description: >
    The Charge Planning Optimizer API computes optimized charging schedules
    for electric fleets based on vehicle availability, energy demand, and
    infrastructure constraints.  
    Optionally, it can generate OCPP-compatible smart charging profiles for
    direct dispatch to charge points.

servers:
  - url: https://api.example.com/optimizer/v1
    description: Production environment

tags:
  - name: Optimization
    description: Endpoints for charging plan optimization

paths:
  /charge-planning:
    post:
      summary: Optimize fleet charging plans
      description: >
        Computes optimized start/end times, EVSE assignments, and optionally
        detailed smart charging profiles for the provided tours.
      tags: [Optimization]
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChargePlanningRequest"
            examples:
              default:
                summary: Example request
                value:
                  companyId: avalon_transportation
                  locationId: aschaffenburg
                  returnOptimizedProfiles: true
                  cluster:
                    id: cluster_01
                    maxLimit: 800000
                  chargePoints:
                    - id: cp_01
                      fullName: Charger North
                      maxLimit: 320000
                    - id: cp_02
                      fullName: Charger South
                      maxLimit: 220000
                  evses:
                    - id: evse_01
                      cpId: cp_01
                      cpName: Charger North
                      fullName: Charger North - Socket A
                      maxLimit: 160000
                      maxCurrentLimit: 250
                    - id: evse_02
                      cpId: cp_01
                      cpName: Charger North
                      fullName: Charger North - Socket B
                      maxLimit: 160000
                      maxCurrentLimit: 250
                  tours:
                    - id: 91Ov9Uj7h-vxokQWXuMJm
                      priority: 2
                      energyDemand: 96.69
                      fromDay: THURSDAY
                      fromTime: "15:00"
                      endDay: TUESDAY
                      endTime: "17:00"
                      vehicle:
                        id: vYbisDjeZFFcYyx0yogX
                        key: AB-TG-2000
                        idTag: 01F2AE40110189
                        capacity: 621
                        avgChaPower: 260
                        thresholdEnergy: 600
                        reducedChaPower: 70
                        systemVoltage: 800
                        maxChaPower: 400
                        minChaPower: 0
      responses:
        "200":
          description: Optimization successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ChargePlanningResponse"
              examples:
                withProfiles:
                  summary: Example with smartChargingProfile
                  value:
                    status: success
                    optimizedTours:
                      - id: 91Ov9Uj7h-vxokQWXuMJm
                        recommendedStartDay: THURSDAY
                        recommendedStartTime: "20:00"
                        recommendedEndDay: FRIDAY
                        recommendedEndTime: "03:30"
                        recommendedTargetSoc: 0.8
                        cp: cp_01
                        evse: evse_01
                        smartChargingProfile:
                          - time: 0
                            power: 123313
                          - time: 4500
                            power: 94971
                          - time: 11100
                            power: 92910
                          - time: 16200
                            power: 0
                    clusterLoadProfile:
                      - timestamp: "2025-10-06T20:00:00Z"
                        power: 180000
                      - timestamp: "2025-10-06T20:05:00Z"
                        power: 190000
        "400":
          description: Bad request – invalid or missing parameters
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: Forbidden – invalid API key
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
      description: API key required for authentication and authorization.

  schemas:
    ChargePlanningRequest:
      type: object
      required:
        - companyId
        - locationId
        - cluster
        - chargePoints
        - evses
        - tours
      properties:
        companyId:
          type: string
          description: Unique identifier of the company performing the optimization.
        locationId:
          type: string
          description: Unique identifier of the physical depot or site.
        returnOptimizedProfiles:
          type: boolean
          description: >
            If true, the optimizer will return for each tour a `smartChargingProfile`
            array showing detailed time–power pairs suitable for OCPP dispatch.
          default: false
        cluster:
          $ref: "#/components/schemas/Cluster"
        chargePoints:
          type: array
          description: List of charge points (stations) available for optimization.
          items:
            $ref: "#/components/schemas/ChargePoint"
        evses:
          type: array
          description: List of EVSE connectors associated with the charge points.
          items:
            $ref: "#/components/schemas/EVSE"
        tours:
          type: array
          description: List of all vehicle tours to be optimized.
          items:
            $ref: "#/components/schemas/Tour"

    Cluster:
      type: object
      required: [id, maxLimit]
      properties:
        id:
          type: string
          description: Unique cluster identifier.
        maxLimit:
          type: number
          description: Maximum power capacity of the cluster in watts.

    ChargePoint:
      type: object
      required: [id, fullName, maxLimit]
      properties:
        id:
          type: string
          description: Unique charge point (station) identifier.
        fullName:
          type: string
          description: Human-readable charge point name.
        maxLimit:
          type: number
          description: Maximum total charger power limit in watts.

    EVSE:
      type: object
      required: [id, cpId, cpName, fullName, maxLimit, maxCurrentLimit]
      properties:
        id:
          type: string
          description: Unique EVSE identifier (individual connector).
        cpId:
          type: string
          description: Identifier of the parent charge point this EVSE belongs to.
        cpName:
          type: string
          description: Name of the parent charge point.
        fullName:
          type: string
          description: Human-readable name for the EVSE (e.g. station + socket name).
        maxLimit:
          type: number
          description: Maximum power limit for the EVSE in watts.
        maxCurrentLimit:
          type: number
          description: Maximum current (in amperes) that can be delivered by this EVSE.

    Tour:
      type: object
      required:
        - id
        - priority
        - energyDemand
        - fromDay
        - fromTime
        - endDay
        - endTime
        - vehicle
      properties:
        id:
          type: string
          description: Unique identifier of the tour or charging session.
        priority:
          type: number
          description: Numeric priority level (higher = more important).
        energyDemand:
          type: number
          description: Required energy demand for the vehicle in kWh.
        fromDay:
          type: string
          description: Earliest weekday when the vehicle is available for charging.
        fromTime:
          type: string
          description: Earliest start time of availability (HH:MM, 24-hour format).
        endDay:
          type: string
          description: Latest weekday when the charging must be completed.
        endTime:
          type: string
          description: Latest end time of availability (HH:MM, 24-hour format).
        vehicle:
          $ref: "#/components/schemas/Vehicle"

    Vehicle:
      type: object
      required:
        - id
        - key
        - idTag
        - capacity
        - avgChaPower
        - maxChaPower
        - minChaPower
        - thresholdEnergy
        - reducedChaPower
        - systemVoltage
      properties:
        id:
          type: string
          description: Unique identifier of the vehicle.
        key:
          type: string
          description: Vehicle license plate or internal key.
        idTag:
          type: string
          description: RFID or authorization identifier used at the charge point.
        capacity:
          type: number
          description: Battery capacity in kilowatt-hours.
        avgChaPower:
          type: number
          description: Average charging power in watts.
        maxChaPower:
          type: number
          description: Maximum charging power the vehicle supports in watts.
        minChaPower:
          type: number
          description: Minimum charging power the vehicle can sustain in watts.
        thresholdEnergy:
          type: number
          description: Energy threshold (in kWh) after which reduced power is applied.
        reducedChaPower:
          type: number
          description: Reduced charging power (in watts) applied beyond the threshold.
        systemVoltage:
          type: number
          description: Nominal DC system voltage of the battery.

    ChargePlanningResponse:
      type: object
      properties:
        status:
          type: string
          enum: [success, error]
          description: Processing status of the optimization.
        optimizedTours:
          type: array
          description: List of tours with assigned start/end times and EVSEs.
          items:
            $ref: "#/components/schemas/OptimizedTour"
        clusterLoadProfile:
          type: array
          description: Optional array describing total cluster power load over time.
          items:
            type: object
            properties:
              timestamp:
                type: string
                format: date-time
                description: Timestamp (UTC) for this power measurement.
              power:
                type: number
                description: Total site power draw in watts at the given time.
        errorMessage:
          type: string
          description: Human-readable error message, present only when status = error.

    OptimizedTour:
      type: object
      properties:
        id:
          type: string
          description: Identifier of the optimized tour.
        recommendedStartDay:
          type: string
          description: Recommended weekday to begin charging.
        recommendedStartTime:
          type: string
          description: Recommended start time for charging (HH:MM).
        recommendedEndDay:
          type: string
          description: Recommended weekday to finish charging.
        recommendedEndTime:
          type: string
          description: Recommended end time for charging (HH:MM).
        recommendedTargetSoc:
          type: number
          description: Optional target state of charge (fraction between 0 and 1).
        cp:
          type: string
          description: Assigned charge point ID.
        evse:
          type: string
          description: Assigned EVSE ID.
        smartChargingProfile:
          type: array
          description: >
            Optional OCPP-compatible smart charging profile showing
            time–power mapping for the recommended charging period.
          items:
            type: object
            properties:
              time:
                type: number
                description: Elapsed time since charging start in seconds.
              power:
                type: number
                description: Charging power in watts at that time.

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Description of the error that occurred.
